name: Compilar informe LaTeX

permissions:
  contents: write

on:
  push:
    branches: [main]

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Compilar LaTeX a PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: informe/latex/main.tex

      - name: Copiar PDF con nombre final
        run: |
          mkdir -p docs
          cp informe/latex/main.pdf docs/Propuesta_SIG_Alimentos_Emy.pdf

      - name: Subir PDF al repositorio
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualiza PDF compilado automáticamente"
          file_pattern: docs/Propuesta_SIG_Alimentos_Emy.pdf
